// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiqXXpqj8kOAkm3JvIxZK7QPeHK_Hkq5k',
    appId: '1:747090737301:web:18f1f33fe191bd8973c39c',
    messagingSenderId: '747090737301',
    projectId: 'sha5er',
    authDomain: 'sha5er.firebaseapp.com',
    storageBucket: 'sha5er.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVcNLChH_BExIg3rLnCHX0EDXvRuIumvU',
    appId: '1:747090737301:android:9f7d350cb5426da373c39c',
    messagingSenderId: '747090737301',
    projectId: 'sha5er',
    storageBucket: 'sha5er.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKo_2wnfCFvme6v6xi7vBth4Sktn78jUY',
    appId: '1:747090737301:ios:6f31c93bf016776273c39c',
    messagingSenderId: '747090737301',
    projectId: 'sha5er',
    storageBucket: 'sha5er.appspot.com',
    iosClientId: '747090737301-36fjvt5om8rshv11ecve68rslam147s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sha5er',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKo_2wnfCFvme6v6xi7vBth4Sktn78jUY',
    appId: '1:747090737301:ios:6f31c93bf016776273c39c',
    messagingSenderId: '747090737301',
    projectId: 'sha5er',
    storageBucket: 'sha5er.appspot.com',
    iosClientId: '747090737301-36fjvt5om8rshv11ecve68rslam147s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sha5er',
  );
}
